### ISSUE TITLE
LMS / Chromecast Bridge Not Loading from LMS Plugins List

### ISSUE THREAD

**Issue by rpgieselman** [philippe44/LMS-to-Cast#1]
Thank you for creating this app, Philippe.

I'm not a techie, but am reasonably knowledgeable about computers and networking.  Based on what I read in the LMS Forum, I went ahead and bought a Chromecast unit and have "installed" it on my network as per the Google's instructions.

I've also checked the Chromecast Bridge plugin in the LMS Server Settings page.  But the server keeps telling me that it must restart, gives me the option to restart now, which I choose, and then just sits there.  I've manually restarted the server, but keep getting the same message.  Needless to say, the Chromecast unit is not showing up in the player list on the LMS.

In addition, Chromecast Bridge no longer shows in the plugin list; it seems to have just disappeared.

I am running LMS off a Synology Server (DS213j).  It has no trouble locating my other players (a SB Radio and a SB Classic.)  All my music is stored on the server in iTunes.

Can you help me figure out what I may be doing incorrectly?

Thanks for any help you can provide.

**Comment by philippe44** [comment]
What do you have the the LMS server log (accessible in the information tab) ? It should tell you if there is an installation problem

**Comment by rpgieselman** [comment]
Hello again, Philippe -

This morning on startup, I encountered the same issue loading the
Bridge plugin.  Every time I navigate to the plugin page, I receive
the "restart" message and then a reminder message stating that the
restart was about to begin.  When I chose "restart now", nothing
seemed to happen.  The Chromecast Bridge plugin was not visible in the
plugin list.

I could not see any error message in the log.

So, I uninstalled and reinstalled LMS, rescanned, and then navigated
to the plugin page.  I was able to find Chromecast Bridge, checked on
it and entered into the same restart "loop".  I shut down LMS in my
browser and in the NAS, then restarted both.  No change.  Because I
reloaded LMS, the log was quite short.  I've pasted it below.  Again,
I don't see that anything is wrong there, but please correct me if I'm
wrong.

Thanks once again for any help you can provide

[16-02-11 10:25:09.6436] main::init (354) Starting Logitech Media
Server (v7.7.3, 1375965195, Mon Aug 19 11:42:55 PDT 2013) perl
5.018004
[16-02-11 10:25:13.4211] Slim::Utils::SQLiteHelper::postConnect (359)
Optimizing DB because of missing or empty sqlite_stat1 table
[16-02-11 10:29:56.5023] main::init (354) Starting Logitech Media
Server (v7.7.3, 1375965195, Mon Aug 19 11:42:55 PDT 2013) perl
5.018004
[16-02-11 10:30:59.4952] main::init (354) Starting Logitech Media
Server (v7.7.3, 1375965195, Mon Aug 19 11:42:55 PDT 2013) perl
5.018004

Russ
c: 412-498-2306

**Comment by rpgieselman** [comment]
Oh and one more thing, once again I cannot find Chromecast Bridge on the
plugin list.  It simply disappears once I've checked and applied it.

Russ
c: 412-498-2306

**Comment by philippe44** [comment]
Unfortunately this is a known problem linked to Syno and where I store my plugins (sourceforge). Sourceforge re-directs you to a https link and Syno does not support SSL in Perl by default. You have to install it and it's a bit of a manual process that is described in the YouTube plugin in the logitech forum. It was one of the known issues I had to face when I took over the YouTube plugin development as well as SSL is mandatory not only for the installation, but for the plugin to work. In your case, there is a workaround which is to manually install, but this requires to use SSH/telent to login intot he Syno

**Comment by rpgieselman** [comment]
So will I be able to do this myself once I find the YouTube video?  Can you provide me with a link to the video?

Thanks again.

Russ

**Comment by philippe44** [comment]
Sorry, I was not clear. The YouTube plugin is another LMS plugin that allow you to use/play YouTube videos in LMS. But meanwhile I had another look and it seems that there is a brand new bigger problem with sourceforge that does currently 3 HTTP redirections, and LMS does not like it, so it might be the issue. Best for you is to SSH to you syno, then go to /volume1@appstore/SqueezeCenter/Plugins and here you unzip the package you've manually downloaded from https://sourceforge.net/projects/lms-plugins-philippe44/files/CastBridge-0.2.0.0.zip/download. Make sure you unzip it under a directory named CastBridge and upon restart of LMS, it should be good

**Comment by rpgieselman** [comment]
Thanks again, Philippe!

I guess I am just dense.  I have manually downloaded the Castbridge plugin
package, but cannot figure out how to open it in the /volume1@appstore
location that you have specified.  I see in the LMS that this is where the
plugins are stored, but cannot find it as a folder or file location on the
server.

I spoke with the folks at Synology and they tell me that to get to this
location, I will have to use the "Command Line" and that they are not
equipped to tell me how to do that.  Can you help me out one more time?

Thank you!

Russ

Russ
c: 412-498-2306

**Comment by philippe44** [comment]
You have to open a SSH connection (using putty or a similar tool) to your Syno and then type the right commands to copy the files in the directory I mentionned before. But if you are not familiar with using command line in Linux (like 'cmd' in Windows), this might be difficult and you might damage things - are you sure you want to try that then ?

**Comment by rpgieselman** [comment]
No, I don't think it would be wise for me to try this.

Thanks for your assistance.  I guess I will have to do something else.

I appreciate your help, Philippe.

Russ

**Comment by philippe44** [comment]
There was a download problem with sourceforge that affected many plugins. I've fixed (hopefully) the problem for mine, you can try again, but I recommend you use the dev version (see the 1 post of the related thread in the LMS forum)

**Comment by rpgieselman** [comment]
Thanks Philippe, I'll give it a try.

I appreciate the followup.

Russ

**Comment by rpgieselman** [comment]
Whooppeeee, it works!

Thanks so much for sticking with me on this, Philippe!

Have a great week.

Russ
c: 412-498-2306
