### ISSUE TITLE
restart required after several hours inactivity

### ISSUE THREAD

**Issue by resuarez** [philippe44/LMS-to-Cast#11]
Since the last update to 1.21.0, I don't get any sound. But, restarting the plugin, the sound returns.  It happens after being inactive the server for several hours.   I've reinstalled the server in another machine and the problem reappears.

I will appreciate any help how I could fix that.

**Comment by philippe44** [comment]
I think I've solved that in the latest version

**Comment by resuarez** [comment]
Thank you very much
