### ISSUE TITLE
can't install the plugin

### ISSUE THREAD

**Issue by hvrba** [philippe44/LMS-to-Cast#13]
Hi Philippe,
I am on raspberry pi with picoreplayer and LMS (7.9.3) and when I tried to install the Chromecast bridge plugin it first looks like it's installed but nope, saying there is an update when selecting the update, then it completely disappears and the plugin is not installed, tried thousand times, and it ignores the installation, never installs it. (did fresh install of the picoreplayer and LMS, still the same thing) Can you help please?

**Comment by philippe44** [comment]
I've updated signatures - can you try again

**Comment by hvrba** [comment]
It's working now, perfect. Thank you
