### ISSUE TITLE
I have just installed the latest version and the Generate button is missing?

### ISSUE THREAD

**Issue by northwinds** [philippe44/LMS-to-Cast#14]
I have just installed the latest version and the Generate button is missing?

Here are my sytem details:

Logitech Media Server Version: 8.0.0 - 1601455867 @ audiodigitale.eu 22-10-2020
Hostname: lms
Server IP Address: 192.168.1.26
Server HTTP Port Number: 9000
Operating system: freebsd - EN - UTF8
Platform Architecture: amd64-freebsd
Perl Version: 5.32.0 - amd64-freebsd-thread-multi
Audio::Scan: 1.02
IO::Socket::SSL: 2.068
Database Version: DBD::SQLite 1.66 (sqlite 3.32.3)

**Comment by philippe44** [comment]
You don't need to use "Generate" anymore but would you mind going to the LMS forum? 

https://forums.slimdevices.com/forum.php

**Comment by northwinds** [comment]
Many thanks for the reply!

Is there any specific post I should look at to fix this?

Cheers,
Craig.

On 24 October 2020 at 22:27:12, philippe44 (notifications@github.com) wrote:

You don't need to use "Generate" any more but would you mind going to the LMS forum?

https://forums.slimdevices.com/forum.php

**Comment by philippe44** [comment]
Look & ask in the dedicated thread https://forums.slimdevices.com/showthread.php?104614-Announce-CastBridge-integrate-Chromecast-players-with-LMS-(squeeze2cast)
