### ISSUE TITLE
Request: Cast-to-LMS?

### ISSUE THREAD

**Issue by iGadget** [philippe44/LMS-to-Cast#15]
First of all, awesome job of creating this wonderful plugin. That said, for my use case I'm wondering if it would be feasible to build it the other way around - to make LMS and/or Squeezebox players a Cast target, so Cast-to-LMS?

**Comment by philippe44** [comment]
Thanks - The reverse is not possible due to the way a CC device works and how applications are ran inside it. It's a security thing by design from Google
