### ISSUE TITLE
Plugin doesn't instal on lms (daphile)

### ISSUE THREAD

**Issue by th2j** [philippe44/LMS-to-Cast#16]
when i tried to install, i have this error :
Slim::Utils::PluginDownloader::_installDownload (215) digest does not match /var/daphile/mediaserver/cache/DownloadedPlugins/CastBridge.zip - CastBridge will not be installed: expected 987dda58eca4db5c1a84c586fba1b5d854639745, got ca55c1e69f3aab2e349ce07d3f9a4d40a024ae80

can you do something please ?
thanks

**Comment by labaland** [comment]
I get the same! in both synology package and when trying docker image! 
was working fine before update, now i cant enable it and listen to music

**Comment by labaland** [comment]
> when i tried to install, i have this error :
> Slim::Utils::PluginDownloader::_installDownload (215) digest does not match /var/daphile/mediaserver/cache/DownloadedPlugins/CastBridge.zip - CastBridge will not be installed: expected 987dda58eca4db5c1a84c586fba1b5d854639745, got ca55c1e69f3aab2e349ce07d3f9a4d40a024ae80
> 
> can you do something please ?
> thanks

Wierd, now it works for me.

**Comment by th2j** [comment]
yes it works for me too now
