### ISSUE TITLE
Remove static text from visual representation

### ISSUE THREAD

**Issue by kongo09** [philippe44/LMS-to-Cast#18]
When streaming to a Chromecast device attached to a TV, the visual shows the static text `Default Media Receiver` at the top left above Album, Song and Artist information.

This text is not only non-informative, but also - as it is static - can hurt the OLED device.

I assume it is presented through this application. Would it be possible to remove it, at least optionally?

**Comment by philippe44** [comment]
No, it would need to write another "media receiver" which I don't have time to do

**Comment by kongo09** [comment]
Oh, sorry, I was hoping that this is simply a text string somewhere?

**Comment by philippe44** [comment]
No, it's a larger change, unfortunately. It's always possible to recompile the default media receiver and I've done that in the past, but it's no very convenient as that means yet another element to maintain. There are signature involved and a few other steps that makes it a bit too much for me in regard of the benefit
