### ISSUE TITLE
Synology : can't see players

### ISSUE THREAD

**Issue by SeeDborg** [philippe44/LMS-to-Cast#20]
Hi,
I've been using LMS with your plugin for months (thank you !), but recently I had to switch to the Docker version on my synology.

I was not to install it (I did not see at first that the container had to run in the same network as host so I could not generate my config file).
I can now generate a config file and start the plugin, but none of my players are appearing in LMS then...

![image](https://user-images.githubusercontent.com/7523821/116826632-4f122c80-ab95-11eb-87d3-25170052a161.png)

Sometimes I have some weird players appearing, only in parameters : 
![image](https://user-images.githubusercontent.com/7523821/116826672-8254bb80-ab95-11eb-9c55-223c92a8de44.png)

**Comment by SeeDborg** [comment]
In my log I have this :


Retarting Squeeze2cast after crash: /config/cache/InstalledPlugins/Plugins/CastBridge/Bin/squeeze2cast-x86-64-static -Z -I -x /config/prefs/castbridge.xml -i /config/prefs/castbridge.xml

Retarting Squeeze2cast after crash: /config/cache/InstalledPlugins/Plugins/CastBridge/Bin/squeeze2cast-x86-64-static -Z -I -x /config/prefs/castbridge.xml

**Comment by philippe44** [comment]
There was a build issue, it should be fixed now

**Comment by SeeDborg** [comment]
I trying uninstalling and reinstalling, but I see no difference. Should I do something special?

**Comment by philippe44** [comment]
You should see version 1.50.1

**Comment by SeeDborg** [comment]
No, it's still 1.50.0 :
![image](https://user-images.githubusercontent.com/7523821/116844958-daff7500-abe4-11eb-907e-a9ec9418d6b1.png)

**Comment by philippe44** [comment]
try to remove the dev repository

**Comment by SeeDborg** [comment]
OK, I'll try it tonight. Can you point a link explaining how to do that please ?

**Comment by philippe44** [comment]
It's on the 1st post of the castbridge thread on LMS forums

**Comment by SeeDborg** [comment]
It updated itself and start working again.

It was really a bad timing, addon was broken just when I reinstalled LMS, I really thought it was my fault ^^

Thanks again for your work.
Regards.

**Comment by philippe44** [comment]
I don't know why I have these bad builds from time to time... it's annoying
