### ISSUE TITLE
Chromecast plugin don't "see" raspberry players

### ISSUE THREAD

**Issue by tutle** [philippe44/LMS-to-Cast#22]
Hello, I have LMS installed on my synology nas and 4 raspberry players with picoreplayer in them.
After installed Chromecast plugin, only the mibox (for TV) is discovered, I don't see the raspberry players.
Do I have to configure something else ?

A line says
`List of players currently in configuration file - Note that more devices might have been discovered
`
Sincerely

**Comment by philippe44** [comment]
I don't understand. This plugin does not interfere with piCore (squeezelite). Do you have them back when you stop the plugin?

**Comment by tutle** [comment]
No what I mean is I can't cast on the players but I still see them in LMS or when I use squeezer and even spotify plugin.

**Comment by philippe44** [comment]
oh, I think you misunderstood the objective of the plugin. It is to have CC players seend by LMS as normal squeezeboxes, not to turn squeezeboxes into CC. That cannot be done

**Comment by tutle** [comment]
Ok, sorry with that. It was to permit external spotify accounts (family) to use LMS without entering their account logins...

**Comment by philippe44** [comment]
NP!
