### ISSUE TITLE
No metadata update during web radio playback

### ISSUE THREAD

**Issue by kirri** [philippe44/LMS-to-Cast#25]
I especially like the option to send meta information to the player, which works great when playing an album.  One of my most listened web radio stream also sends meta information for all played songs separately. Although LMS notices the change when a new song starts, the player does not update. To then get current track and cover art information displayed, I have to press skip, then the stream reconnects and the information is updated. Is there a way to notify the player when the track information changes on a web radio stream?
Example stream: https://streams.egofm.de/egoFM-hq

**Comment by philippe44** [comment]
It is a limitation of Chromecast protocol that does not support in-band metadata update

**Comment by kirri** [comment]
Oh, I see. That's a pity. Thanks for the quick response and your great plugin, Philippe!
