### ISSUE TITLE
Plugin doesn't start (Cannot start mDNS searcher)

### ISSUE THREAD

**Issue by th2j** [philippe44/LMS-to-Cast#26]
Hello,
i didn't use the plugin for a while, but this morning i tried tu use it and it doesn't start.
it was working before and i didn't change the parameters.

here is the logs : 
Starting Squeeze2cast: /var/daphile/mediaserver/cache/InstalledPlugins/Plugins/CastBridge/Bin/squeeze2cast-x86-64-static -Z -I -f /var/daphile/mediaserver/log/castbridge.log -d all=debug -x /srv/mediaserver/prefs/castbridge.xml
[11:00:07.585837] main:1268 Starting squeeze2cast version: v1.82.2 (Feb 21 2022 @ 19:01:49)
[11:00:07.586126] register_alac:541 using alac to decode alc
[11:00:07.586168] register_mad:433 using mad to decode mp3
[11:00:07.586190] register_faad:647 using faad to decode aac
[11:00:07.586210] register_vorbis:346 using vorbis to decode ogg
[11:00:07.586230] register_pcm:339 using pcm
[11:00:07.586249] register_flac:313 using flac to decode flc
[11:00:07.586269] register_opus:286 using opus to decode ops
[11:00:07.586288] register_m4a_thru:307 using mp4 to aac (ADTS)
[11:00:07.586308] register_flac_thru:212 using flac
[11:00:07.586327] register_thru:106 using thru
[11:00:07.586347] register_soxr:394 using soxr for resampling
[11:00:07.586366] Start:1036 Binding to 192.168.31.68 (http:0)
[11:00:07.586795] Start:1046 Cannot start mDNS searcher
[11:00:07.586843] main:1307 Cannot start, exiting

Retarting Squeeze2cast after crash: /var/daphile/mediaserver/cache/InstalledPlugins/Plugins/CastBridge/Bin/squeeze2cast-x86-64-static -Z -I -x /srv/mediaserver/prefs/castbridge.xml

Thanks
Thomas

**Comment by philippe44** [comment]
It looks like something has changes in your network configuration. Likely a firewall or something that prevents the search for players to be launched

**Comment by th2j** [comment]
Thanks for your reply

i am on Daphile (21.12-b051729-x86_64-rt), LMS is 8.2.1

I tried to remove the plugin, erase the prefs file to restart from a new
install,
but now the castbridge.xml is missing and i can't generate one,

Le mer. 24 août 2022 à 18:34, philippe44 ***@***.***> a
écrit :

**Comment by th2j** [comment]
some updates :

i succeeded to generate a new castbridge.xml (by copying from another
machine and regenerate),
but the plugin is not working

here is the castbridge file :
<squeeze2cast>
  <cast_log>info</cast_log>
  <stream_log>warn</stream_log>
  <slimmain_log>warn</slimmain_log>
  <device>
    <mac>cc:cc:c0:db:d7:7d</mac>
    <enabled>1</enabled>
    <udn>dbac066c2de58fc3396447fa82f550c9</udn>
    <friendly_name>Google mini</friendly_name>
    <name>Google mini</name>
  </device>
  <device>
    <mac>cc:cc:07:e9:cd:ba</mac>
    <udn>b79c09933d84fc51087ed5b0aff7e6c5</udn>
    <enabled>1</enabled>
    <friendly_name>Chromecast Ultra</friendly_name>
    <name>Chromecast Ultra</name>
  </device>
  <util_log>warn</util_log>
  <binding>?</binding>
  <decode_log>warn</decode_log>
  <main_log>info</main_log>
  <common>
    <stop_receiver>0</stop_receiver>
    <stream_length>-1</stream_length>
    <auto_play>0</auto_play>
    <sample_rate>96000</sample_rate>
    <volume_on_play>1</volume_on_play>
    <send_metadata>1</send_metadata>
    <output_size>4194304</output_size>
    <send_coverart>1</send_coverart>
    <enabled>1</enabled>
    <send_icy>0</send_icy>
    <streambuf_size>1048576</streambuf_size>
    <mode>thru</mode>
    <flac_header>1</flac_header>
    <next_delay>15</next_delay>
    <remove_timeout>0</remove_timeout>
    <codecs>aac,ogg,ops,ogf,flc,alc,wav,aif,pcm,mp3</codecs>
    <media_volume>50</media_volume>
    <roon_mode>0</roon_mode>
    <volume_feedback>1</volume_feedback>
    <server>?</server>
  </common>
  <output_log>warn</output_log>
  <log_limit>-1</log_limit>
  <slimproto_log>info</slimproto_log>
</squeeze2cast>

**Comment by philippe44** [comment]
Creating a config file will not help. If none is generated then there is no player detected or the bridge is not starting. This is the latter in your case but as told, it means something is interfering with your networking configuration. Maybe you have daphile running in a VM ?

**Comment by th2j** [comment]
the bridge crash at startup,
it is a regular Daphile install, and i didn't change anything in my network recently,
it is the same with wifi or ethernet

**Comment by philippe44** [comment]
No it does not crash, look at the previous log lines : it exits because it cannot start the mdns (device) searcher. The monitoring thread see that it has exited and cannot differentiate from a crash, hence the log. Anyway, do you have multiple network interfaces? If you do, try to force the bridge to use what LMS uses

**Comment by th2j** [comment]
ok thanks for helping, i tried but this is not working for me

**Comment by th2j** [comment]
ok i succeeded to make it work : 

i remove le line "disallow-other-stacks=yes"
in the file /etc/avahi/avahi-daemon.conf

Thanks for your help
