### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by Maciekw1000** [philippe44/LMS-to-Cast#28]
Hi, I have been using chromecast brigde for several months. Super job, fantastic plugin. So now I am really sad, because after reinstalling max2play and LMS on raspeberry pi , I can't install Chromecast bridge plugin. It is visible in the list, but after selecting and restarting LMS nothing happens - it is not in the list of installed plugins. Sometimes I get a message about updating the plugin, and sometimes it just disappears from all lists.

**Comment by philippe44** [comment]
What pi are tou using ?

**Comment by Maciekw1000** [comment]
Hi, Thanks for the quick reply.

I'm using a Raspberry pi 4 4gb RAM. There is the following message in the login file: 
"[23-01-15 09:52:17.0587] Slim::Utils::PluginDownloader::_downloadError (266) unable to download CastBridge from http://downloads.sourceforge.net/project/lms-plugins-philippe44/CastBridge-1.82.2.zip - Connect timed out:".

I don't have this problem when installing other plugins.

**Comment by philippe44** [comment]
It means that your access to sourceforge has an issue. Can you use curl or wget to the url you mentioned? I checked and the file is there

**Comment by Maciekw1000** [comment]
I tried downloading the plugin file using the download station on qnap. Unfortunately I received a message that the file could not be accessed. 
The same applies to your other plugin - UPnPBridge. Again, updating the plug-in is not possible. And access to the file is blocked. :(

**Comment by philippe44** [comment]
This is an issue with your internet access from the qnap, I'm afraid or your have a version of LMS that is either too old or does not include proper SSL support

**Comment by Maciekw1000** [comment]
I tried out several versions of the LMS yesterday. From 8.1.2 to the latest nightly versions 8.3 and 8.4. Unfortunately it doesn't work on any of them.

**Comment by philippe44** [comment]
I would suggest asking on the LMS forum

**Comment by Maciekw1000** [comment]
Situation explained. My ISP blocked sourceforge downloads. Thus, none of the plugins that are downloadable via LMS from the sourceforge repository are possible for me to install. Plug-ins placed in other repositories are available. LMS downloads them without any problem.

**Comment by philippe44** [comment]
Pretty amazing from an ISP to do that. Content filtering is unacceptable, switch if you can.

**Comment by Maciekw1000** [comment]
I changed the ISP. Everything is working. The problem is solved. I am happy.
