### ISSUE TITLE
v2.1.13  vanishing  player

### ISSUE THREAD

**Issue by Thomas-O** [philippe44/LMS-to-Cast#29]
Hello,

After updating to v2.1.13 one of my two chromecast players disappears from the LMS player's list at least once a day. If I restart the Chromecast Bridge plugin (via the plugin's setting page) or reboot the SBC then both players return to the list. This hasn't been an issue before. Appearing only since the recent update.

**Comment by philippe44** [comment]
Please go to the LMS forums and post a log of the bridge (not the LMS server log)
