### ISSUE TITLE
Odd behavior

### ISSUE THREAD

**Issue by dgiffen** [philippe44/LMS-to-Cast#4]
I have had some issues with local files. I'm using a Vizio TV with a vizio soundbar, both are cast enabled. When I add something from Spotify, all plays normal. But when I que a local file, I get no audio on either the TV or the soundbar. Adding some local files after Spotify works, but then quits and I have restart LMS to get it working again. I also have a google home and it works without issue. Spotify direct to the TV works as expected.

**Comment by philippe44** [comment]
Have you tried the latest update? I did a few tweaks wrt volume management which could have explained your issue

**Comment by dgiffen** [comment]
I applied the latest update and it indeed is working correctly.
Thank you so much for this
Doug

**Comment by philippe44** [comment]
Good - I'll close the issue then

**Comment by dgiffen** [comment]
Once again thank you for the help and the great plug in

Thanks
Doug

On Dec 25, 2016 2:02 PM, "philippe44" <notifications@github.com> wrote:

Good - I'll close the issue then

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/philippe44/LMS-to-Cast/issues/4#issuecomment-269133838>,
or mute the thread
