### ISSUE TITLE
Sync support?

### ISSUE THREAD

**Issue by herder** [philippe44/LMS-to-Cast#6]
First of all: huuge thanks for this plugin! 

I was wondering if synchronisation between multiple players is supposed to work? I have almost 2 seconds difference between my nodes (a mix of Chromecast Audio, Nividia Shield with Cast, and PiCorePlayer on RPi)

I have no idea if this is even possible or worthwhile, but thought I'd ask anyway :)

**Comment by philippe44** [comment]
Thanks - Google has not published their sync protocol, so I can't synchronize CC's with SB. You can get synchronization amongst CC's. Every group created using Google's application will be an extra player in LMS

**Comment by herder** [comment]
Aha, too bad. Let's hope they publish the protocol soon.
Thanks!
