### ISSUE TITLE
LMS loses CCA from Choose Player list

### ISSUE THREAD

**Issue by macekw** [philippe44/LMS-to-Cast#7]
Hello,
LMS v7.7.5 is installed on CentOS Linux release 7.4.1708 machine, with Chromecast bridge v0.2.12.0 plugin. I have Chromecast (2nd gen) and Chromecast Audio in my home network. Both can be seen in Plugin settings:

Chromecast Audio	 cc:cc:fd:XX:XX:XX	 QWERTYUIOPASDFGHJKLZXCVBNM123456	Chromecast Audio
Chromecast 2nd Gen	 cc:cc:9f:XX:XX:XX	 QWERTYUIOPASDFGHJKLZXCVBNM123456	Chromecast 2nd Gen

both of them are checked to be used.
When I restart LMS with systemctl command it will show me CC and CCA in the main 'Chose Player' LMS drop-down menu. However after some time, and for me due to unknown reason, the CCA disappears from that menu . I started to observe this issue after plugin upgrade about two months ago. Not sure if this was  v0.2.10.0. The earlier plugin I had been using was issued beginning of this year. I do not recall the version. I have your repo added to "Additional Repositories" as follows:
http://downloads.sourceforge.net/project/lms-plugins-philippe44/repo-sf.xml
The plugin cache is empty
/var/lib/squeezeboxserver/cache
Can you please help to identify the issue? I can provide more logs as necessary.

Thank you
macekw

**Comment by macekw** [comment]
_The earlier plugin I had been using was issued beginning of this year._
I meant beginning of 2017 of course :-)

**Comment by philippe44** [comment]
I did not change recently the detection mechanism. Any changes in your network configuration?

**Comment by macekw** [comment]
@philippe44, thank you for sticking with me. I've re-adjusted my router's WiFi settings and problem went away. Let the LMS thrive! 
All the best!

**Comment by philippe44** [comment]
Thanks - I also have a new version under test which should largely improved detection
