### ISSUE TITLE
Repository Location for Logitech Media Server Version: 7.7.6 ?

### ISSUE THREAD

**Issue by echable9999** [philippe44/LMS-to-Cast#9]
Hi

Just installed LMS on my Synology DS415PLAY NAS. 

Found a link somewhere to the development version of your plugin, this now shows up with a heading at the bottom of the plugin list, but with no actual plugin listed underneath it, and no Chromecast Bridge anywhere in the plugin list.

What is the address for the non-development version for Chromecast Bridge that I need to enter into LMS settings ? 

I could only find links to Sourceforge pages etc. that had zip version of the files, don't know how I could use that. 

Thank you!

**Comment by philippe44** [comment]
it's in the "official" 3rd party plugins, no need to add any repository
